### ISSUE TITLE
Installed, but can't login

### ISSUE THREAD

**Issue by Omertron** [markvader/sonic_hacs#9]
Installed and started config.

When trying to put in username and password, I get an "! Unexpected Error".

Password is 40 chars long if that makes a difference

**Comment by markvader** [comment]
Thanks @Omertron As we've discussed on discord and for anyone else that might find themselves here, you need to log into the integration with an email and password registered with Hero Labs, rather than with any oauth provider (Google/Facebook) details that you are also able to log into the Sonic app with.  I will improve the documentation to provide detail on this.

**Comment by Omertron** [comment]
Problem solved, thanks for the quick response
